name: Go package

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      # action文档：
      # https://github.com/marketplace/actions/postgresql-in-github-actions
      - uses: nnhy/postgresql-action@v1.0

      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      - name: Test
        run: go test -v ./...
        env:
          STORAGE_LOCK_POSTGRESQL_DSN: "host=127.0.0.1 user=postgres password=postgres port=5432 dbname=postgres sslmode=disable"